# Generated by Django 3.1.5 on 2021-01-10 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurementconvertmodel',
            name='amount',
            field=models.CharField(max_length=100),
        ),
    ]
