# Generated by Django 3.1.5 on 2021-01-10 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210110_0209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurementconvertmodel',
            name='amount',
            field=models.IntegerField(max_length=100),
        ),
    ]
