# Generated by Django 3.1.5 on 2021-01-09 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MeasurementConvertModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_unit', models.CharField(max_length=20)),
                ('to_unit', models.CharField(max_length=20)),
                ('amount', models.IntegerField(default=1)),
            ],
        ),
    ]
